services:
  mariadb:
    image: mariadb:11
    container_name: karbuh-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: karhub
      MARIADB_USER: karhub_user
      MARIADB_PASSWORD: karhub_pass
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: